package com.falapet.context.application;
import java.time.Instant; import java.util.*; import org.springframework.stereotype.Service;
import com.falapet.context.domain.ContextType; import com.falapet.shared.contract.http.*; import com.falapet.shared.contract.idempotency.RequestFingerprint; import com.falapet.shared.contract.pagination.*; import tools.jackson.databind.ObjectMapper;
@Service public final class ContextTypeService {
 private final ContextTypeStore store; private final SignedCursorCodec cursors; private final RequestFingerprint fingerprints; private final ObjectMapper json;
 ContextTypeService(ContextTypeStore s,SignedCursorCodec c,RequestFingerprint f,ObjectMapper j){store=s;cursors=c;fingerprints=f;json=j;}
 public ContextType create(UUID tutor,String key,Map<String,Object> body){if(key==null||key.isBlank()||body==null||!body.keySet().equals(Set.of("name")))throw invalid();return store.create(tutor,key,fingerprints.forJson(json.writeValueAsBytes(body)),name(body.get("name")));}
 public ContextType find(UUID tutor,UUID id){return store.find(tutor,id).orElseThrow(()->new ContractException(ErrorCode.RESOURCE_NOT_FOUND));}
 public PageData<ContextType> list(UUID tutor,String status,String cursor,Integer limit){String f=status==null||status.isBlank()?"ACTIVE":status;if(!Set.of("ACTIVE","INACTIVE","ALL").contains(f))throw invalid();var p=CursorPageRequest.of(cursor,limit);Instant at=null;UUID id=null;String scope="context-type.list."+fingerprints.forText(tutor.toString());if(cursor!=null&&!cursor.isBlank())try{var s=cursors.decode(cursor);if(!scope.equals(s.scope())||!f.equals(s.filterFingerprint())||s.position().size()!=2)throw new InvalidCursorException();at=Instant.parse(s.position().get(0));id=UUID.fromString(s.position().get(1));}catch(Exception e){throw new ContractException(ErrorCode.INVALID_CURSOR);}var rows=store.list(tutor,f,at,id,p.limit()+1);boolean more=rows.size()>p.limit();var items=more?rows.subList(0,p.limit()):rows;String next=more?cursors.encode(new CursorState(scope,f,List.of(items.getLast().createdAt().toString(),items.getLast().id().toString()))):null;return new PageData<>(items,new PageMetadata(next,more));}
 public ContextType update(UUID tutor,UUID id,long v,Map<String,Object> body){if(body==null||!body.keySet().equals(Set.of("name")))throw invalid();var current=find(tutor,id);if(current.version()!=v)throw conflict(current);return store.update(tutor,id,v,name(body.get("name"))).orElseThrow(()->conflict(find(tutor,id)));}
 public ContextType status(UUID tutor,UUID id,String value){find(tutor,id);return store.status(tutor,id,value).orElseThrow(()->new ContractException(ErrorCode.RESOURCE_NOT_FOUND));}
 private String name(Object value){if(!(value instanceof String s))throw invalid();s=s.trim();if(s.isEmpty()||s.length()>80||s.codePoints().anyMatch(Character::isISOControl))throw invalid();return s;} private ContractException invalid(){return new ContractException(ErrorCode.VALIDATION_ERROR);} private ContractException conflict(ContextType c){return new ContractException(ErrorCode.VERSION_CONFLICT,null,Map.of("contextType",c));}
}
